### PR TITLE
Add a file about how to structure cozy-apps

### PR DESCRIPTION
**Pull request by aenario**
RFC

### CODE REVIEW

**Comment by frankrousseau** [comment]
To run properly on Americano, the `server.coffee` file requires a `start` function. Do we include it in our guidelines or do we keep it in Cozy Light guides?

**Comment by jsilvestre** [comment]
## Server-side locales
I don't know if splitting locale files is a good idea. On the one hand it seems logical that we try to build two separate apps which run together. On the other hand, it's seems easier to maintain. Just raising the point, I don't have an opinion yet, thus I think I preferer the solution you suggest (splitting server and client).

## Helpers / Libs / Middlewares
I do think there is a difference between `lib` and `helpers`: `helpers` are collections of functions, `libs` are singletons. Middlewares are functions with a specific signature, they could be in `helpers` with an explicit name e.g. "error_middleware.coffee"

## About singletons
Also singletons should be exported like this:
```coffeescript
class MySingleton
    # do whatever you want

_instance = new MySingleton()
module.exports.MySingleton = MySingleton
module.exports.getInstance = -> return _instance
```
So they are more easily testable. If you agree, I will keep using this pattern for future singletons.
Another idea would be to find a dependcy injection pattern that would work as an express middleware, but I'm pretty sure you will be against it as it adds more bloat than it solves problem (and I agree).

## Question
1. What about the initializers we have in some apps, like Home? I think a folder "initializers" is good.
2. Also, where do we do the "stuff to do at startup". Currently it's mostly done in server.coffee in the start's callback, but we don't use the beforeStart and afterStart hooks.

**Comment by frankrousseau** [comment]
The singleton discussion is more complex than it looks. The javascript node way to write code is to rely a lot on modules. Modules look a lot like singleton. I don't know if we should force to use class singleton.

**Comment by jsilvestre** [comment]
I think you missed my point, the idea is to be able to export singleton with its behaviour and an instanciable version of the code to run it in isolation. You may or may not use a class, and I don't see a reason why we should use a specific "singleton" class. It's just about testability. Replace "MySingleton" by "LocalizationManager", "Paas" or whatever singleton we use.

**Comment by aenario** [comment]
# exports.start
+1 on setting it as a .start function (done)

# libs
Regarding libs vs helpers, why not but we should explicit it in this document

#singletons, there is basically 2 options : 
1. Using modules
```coffee
someReference = something()
module.exports.doStuff -> someReference.doStuff()
```

2. using class
```
class Manager
    constructor: ->
        @someReference = something()
   doStuff: -> @someReference.doStuff()

module.exports = new Manager()
# no need for complicated exports
# tests can do new require('...').constructor
```

The problem Joseph has with 1 is that its impossible to unit-test without some hack such as https://www.npmjs.com/package/proxyquire

# initializers folder
I am against it, it should be done in config.beforeStart/afterStart or in a helper/libs file if its too big.

**Comment by jsilvestre** [comment]
# initializers folder
> I am against it, it should be done in config.beforeStart/afterStart or in a helper/libs file if its too big.
That makes sense to me, as long as "patch" are a separated like in a "patch" subfolder (it's just about semantic / clarity).

**Comment by frankrousseau** [comment]
### Singelont

Could you make things clearer about why it's more testable and why it's mandatory to write things the POO way instead to write things the modular way? 

### Directory naming

About `helpers` and `lib` names, I propose that definitions:

* `helpers`: Helpers that don't require other libs than other helpers or NPM package. A good test for a helper is: can I publish it on NPM as a traditional library?
* `helpers/middlewares`: Helpers  that don't require other libs than other helpers or NPM package to be used as Express middleware.
* `lib`: Helpers that are tied to the internal code.
* `lib/middlewares`: Helpers that are tied to the internal code and that are aimed to be used as Express middleware.

**Comment by jsilvestre** [comment]
I tried to demonstrate the problem here: https://gist.github.com/jsilvestre/e53b61d6ce0d9d777d59

Let me know if you need further information.

**Comment by frankrousseau** [comment]
I'm not convinced by the example. You problem can be solved with a reset function that will reset the private variables each time you want to run a new test.

**Comment by frankrousseau** [comment]
I think it's more a matter of taste than real design problems. I don't mind doing POO since it's more the way Coffeescript work. But I prefer chose it as a preferecen rather than as a mandatory solution for testing.

**Comment by jsilvestre** [comment]
I completely agree, sorry, I didn't mean to say it's the only way, even if it's how I sound. I wanted to point out the problem and suggested a solution (I find easier to reason in POO for testing singletons, so my solution was that). I should have been more clear about my opinion in the examples, I want to be able to test a singleton in isolation without overriding `require`, if it's a class, good, if it's a reset method, that's good too. The point is testability, not implementation details.

**Comment by jsilvestre** [comment]
So I just had to test a file not done with a class. It's been workeing fine until I wanted to mock some functions that others are depending on.  See: https://gist.github.com/jsilvestre/f62391c20230b74404eb
It works for sure, but I think the syntax would be better with a class.

**Comment by frankrousseau** [comment]
I merged it. If you don't like something in it. Feel free to open another PR.

**Pull request merged**
