### PR TITLE
Stylus guidelines proposal

### PR DESCRIPTION
**Pull request by m4dz**
I propose those improvements to Stylus files and CSS guidelines. Let's debate :)

### CODE REVIEW

**Comment by frankrousseau** [comment]
I'm ok with it.

**Comment by frankrousseau** [comment]
I will add:

* 4 spaces indentation (because there is no brackets)

**Comment by frankrousseau** [comment]
@jsilvestre @aenario @clochix what do you think about it?

**Comment by jsilvestre** [comment]
+1 except that ordering properties in the order you suggest is quite hard if you don't know what you are doing (like me). So I might need a cheatsheet :)

**Comment by m4dz** [comment]
All right! So in order to help @jsilvestre (and others) when they're doing styles:
Using Stylus to design webapps
I'll write a cheatsheet / guideline on how to order properties and write maintainable stylesheets :wink:…

**Comment by frankrousseau** [comment]
@clochix Don't hesitate to propose change when you will be back.

**Pull request merged**
