### PR TITLE
feat: add note on emoji use

### PR DESCRIPTION
**Pull request by GoOz**
Fixes: #48

### CODE REVIEW

**Comment by gregorylegarec** [comment]
I do not agree as a commit message like
> feat: ✨ Add something
is perfectly correct.

On the other hand,
> ✨ feat: Add something
should not be used anymore.

**Comment by enguerran** [comment]
The guidelines are only recommendations, it is not necessary to waste time to decide the colour of the bike sheding. To be less conclusive, let's just give a note about the developer responsibility regarding the git history readability.

> Please use emojis with the will to improve the understanding of the commits messages. Before, after, in the middle of the subjet, you decide but with good motivations.

**Comment by gregorylegarec** [comment]
Maybe I am wrong but #48 does not say anything about not using 
> feat: ✨ Add something

So to me the guildeline should just be _Feel free to use emoji except before prefix_.

**Comment by GoOz** [comment]
> So to me the guildeline should just be Feel free to use emoji except before prefix.

I tend to agree but I'm not part of those bothered by the emojis so I'm definitely not neutral.

@drazik @ptbrowne what do you think?

**Comment by drazik** [comment]
It's OK for me. For me, the most important thing is that there's no emoji before the type and therefore no need for a specific parser when we setup things that automatically analyze commit messages.

(I also think we've discussed about emojis for way too long :stuck_out_tongue_winking_eye:)

**Comment by ptbrowne** [comment]
:shipit:

**Comment by gregorylegarec** [comment]
Thanks @GoOz 🙃

**Pull request merged**
